//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodicTable
    {
        public int AtomicNumber { get; set; }
        public string Element { get; set; }
        public string Symbol { get; set; }
        public decimal AtomicMass { get; set; }
        public int NumberofNeutrons { get; set; }
        public int NumberofProtons { get; set; }
        public int NumberofElectrons { get; set; }
        public int PeriodNumber { get; set; }
        public Nullable<int> GroupNumber { get; set; }
        public string Phase { get; set; }
        public string Radioactive { get; set; }
        public string Natural { get; set; }
        public string Metal { get; set; }
        public string Nonmetal { get; set; }
        public string Metalloid { get; set; }
        public string ElementType { get; set; }
        public Nullable<decimal> AtomicRadius { get; set; }
        public Nullable<decimal> Electronegativity { get; set; }
        public Nullable<decimal> FirstIonization { get; set; }
        public Nullable<decimal> Density { get; set; }
        public Nullable<decimal> MeltingPoint { get; set; }
        public Nullable<decimal> BoilingPoint { get; set; }
        public Nullable<int> NumberOfIsotopes { get; set; }
        public string Discoverer { get; set; }
        public Nullable<int> DiscoverYear { get; set; }
        public Nullable<decimal> SpecificHeat { get; set; }
        public int NumberofShells { get; set; }
        public Nullable<int> NumberofValence { get; set; }
        public Nullable<int> Row { get; set; }
        public Nullable<int> Column { get; set; }
    }
}
